language: node_js
sudo: false
node_js:
- 9
install:
- yarn
- npm i -g travis-ci-cloudfront-invalidation
script:
- yarn build
cache:
  - yarn
deploy:
- provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    repo: metafetish/buttplug.io
    branch: master
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: buttplug.io
  region: us-west-1
  acl: public_read
  local_dir: buttplug.io
  skip_cleanup: true
  on:
    repo: metafetish/buttplug.io
    branch: master
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
