language: node_js
sudo: false
node_js:
- 9
install:
- yarn
- npm i -g travis-ci-cloudfront-invalidation
script:
- yarn build
cache:
  - yarn
deploy:
- provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    repo: metafetish/buttplug.io
    branch: master
